/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/visit-reviews/{reviewId}/likes/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * 방문 후기 좋아요 등록
         * @description 방문 후기에 좋아요를 등록합니다. (본인이 작성한 후기에는 좋아요 불가)
         */
        put: operations["like"];
        post?: never;
        /**
         * 방문 후기 좋아요 취소
         * @description 이전에 등록한 방문 후기 좋아요를 취소합니다.
         */
        delete: operations["unlike"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/saved-resources/places/{placeId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * 장소/한옥 북마크 및 찜하기 저장
         * @description 특정 장소 또는 한옥을 내 보관함에 찜하기(저장) 처리합니다.
         */
        put: operations["savePlace"];
        post?: never;
        /**
         * 장소/한옥 북마크 저장 취소
         * @description 내 보관함에서 저장된 장소를 삭제합니다.
         */
        delete: operations["deletePlace"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/saved-resources/odii-stories/{storyId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * 오디 오디오 도슨트 스토리 북마크/저장
         * @description 특정 오디 오디오 스토리를 내 보관함에 저장(북마크)합니다.
         */
        put: operations["saveOdii"];
        post?: never;
        /**
         * 오디 오디오 도슨트 스토리 북마크/저장 취소
         * @description 보관함에 저장해 둔 오디 오디오 스토리를 삭제합니다.
         */
        delete: operations["deleteOdii"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/v1/corpus/revisions/{revisionId}/ack": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 코퍼스 동기화 완료 수신확인(ACK)
         * @description FastAPI AI 서비스가 리비전 문서 색인을 완료한 후 수신 확인(ACK)을 전송합니다.
         */
        post: operations["acknowledge"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/visit-reviews/{reviewId}/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 방문 후기 신고 접수
         * @description 부적절하거나 유해한 방문 후기를 신고합니다. (본인 작성 후기는 신고 불가)
         */
        post: operations["report"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/saved-journeys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 내가 저장한 AI 여정 목록 조회
         * @description 로그인한 회원이 보관함에 저장해 둔 여정 목록을 커서 페이징 방식으로 조회합니다.
         */
        get: operations["list"];
        put?: never;
        /**
         * 완성된 AI 여정 코스 내 보관함에 저장
         * @description AI 탐색으로 구성된 여행 코스를 회원의 저장 여정 목록에 보관합니다.
         */
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/saved-journeys/{savedJourneyId}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 저장된 여정으로부터 AI 탐색 재개 (Resume)
         * @description 과거에 저장해 둔 여정 스냅샷을 기반으로 새로운 AI 대화 세션을 생성하여 여행 계획을 이어서 수정/탐색합니다.
         */
        post: operations["resume"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/places/{placeId}/visit-reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 특정 장소의 방문 후기 목록 조회
         * @description 장소 ID(placeId)에 등록된 방문 후기들을 커서 페이징 방식으로 조회합니다.
         */
        get: operations["listPlaceVisitReviews"];
        put?: never;
        /**
         * 방문 후기 작성 (멱등성 보장)
         * @description 특정 장소에 방문 후기를 작성합니다. 멱등성 키(Idempotency-Key)를 지원하여 중복 제출을 방지합니다.
         */
        post: operations["createReview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/operations/moderation/visit-reviews/{reviewId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 운영자 후기 검수 및 상태 변경
         * @description 운영자가 신고되거나 검수 대기 중인 후기를 승인(PUBLISHED), 숨김(HIDDEN), 삭제(DELETED) 처리합니다.
         */
        post: operations["moderate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/explorations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * AI 여정 탐색 세션 생성 (비동기 런 접수)
         * @description 여행 질의(query), 지역 코드(regionCode)를 전달하여 AI 여정 탐색 세션을 생성하고 비동기 생성 런(Run)을 시작합니다.
         */
        post: operations["create_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/explorations/{explorationId}/turns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * AI 대화 턴 추가 (추가 질의/피드백)
         * @description 기존 여정 탐색 세션에 사용자의 추가 요구사항이나 명확화 응답(clarificationAnswer)을 전달하여 새로운 AI 런을 실행합니다.
         */
        post: operations["createTurn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/explorations/{explorationId}/runs/{runId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 진행 중인 AI 실행 런(Run) 취소
         * @description 대기열(QUEUED) 또는 실행 중(RUNNING)인 AI 추천 생성을 즉시 취소합니다.
         */
        post: operations["cancelRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/explorations/{explorationId}/actions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 여정 수정 액션 적용 (PIN, EXCLUDE, PROPOSAL)
         * @description 코스 내 장소 고정(PIN), 제외(EXCLUDE), AI 추천 제안 수락/거절(APPLY_PROPOSAL, DISMISS_PROPOSAL) 액션을 적용합니다.
         */
        post: operations["applyAction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 로그아웃
         * @description 현재 활성화된 회원 세션을 만료시키고 세션 쿠키를 삭제합니다.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/v1/corpus/revisions/{revisionId}/manifest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 코퍼스 리비전 매니페스트 조회
         * @description 특정 리비전 ID에 포함된 모든 청크 및 문서 메타데이터 목록을 조회합니다.
         */
        get: operations["manifest"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/v1/corpus/revisions/{revisionId}/documents/{documentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 코퍼스 단일 문서 내용 조회
         * @description 특정 리비전에 속한 개별 문서의 원문 및 청크 상세 내용을 조회합니다.
         */
        get: operations["document"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/kakao/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 카카오 소셜 로그인 시작 (OAuth2 인가 코드 요청)
         * @description PKCE 보안 검증 및 Nonce 쿠키를 설정하고 카카오 로그인 인증 페이지로 302 리다이렉트합니다.
         */
        get: operations["startLogin"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/kakao/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 카카오 소셜 로그인 콜백 (인가 코드 수신 및 세션 발급)
         * @description 카카오 인증 서버로부터 수신한 인가 코드를 검증하고 토큰을 교환하여 회원 세션 쿠키(__Host-onmaru-session)를 발급한 뒤 프론트엔드로 303 리다이렉트합니다.
         */
        get: operations["completeLogin"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/csrf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * CSRF 토큰 및 게스트 세션 발급
         * @description 상태 변경(POST/PUT/PATCH/DELETE) API 호출 시 CSRF 방어를 위한 헤더 토큰 및 쿠키를 발급하며, 비회원인 경우 게스트 식별용 쿠키를 함께 설정합니다.
         */
        get: operations["csrfToken"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/visit-reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 방문 후기 목록 조회 (글로벌/지역 범위)
         * @description 스코프(ALL, REGION, MY 등)와 행정구역 코드를 지정하여 커서 페이징 방식의 방문 후기 피드를 조회합니다.
         */
        get: operations["listVisitReviews"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/visit-review-regions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 1.2 행정구역 목록 및 방문 후기 통계 조회
         * @description 시/도(1단계) 또는 특정 시/도 하위의 시/군/구(2단계) 행정구역 목록과 각 구역별 누적 방문 후기 건수/지도 메트릭을 조회합니다.
         */
        get: operations["listVisitReviewRegions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/saved-resources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 내가 저장한 리소스 목록 조회 (PLACE / ODII_STORY)
         * @description 타입(type: PLACE 또는 ODII_STORY)별로 회원이 저장한 리소스 목록을 커서 페이징 방식으로 조회합니다.
         */
        get: operations["list_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/saved-journeys/{savedJourneyId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 저장된 AI 여정 상세 조회
         * @description 저장된 여정 ID(savedJourneyId)를 기반으로 코스 스냅샷, 방문 순서, 포함된 장소 상세 정보를 조회합니다.
         */
        get: operations["get"];
        put?: never;
        post?: never;
        /**
         * 저장된 AI 여정 삭제
         * @description 보관함에 저장된 여정을 삭제합니다.
         */
        delete: operations["delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/regions/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * GPS 좌표 기반 행정구역 역지오코딩 해석 (Point-in-Polygon)
         * @description 위도(lat)와 경도(lng) 좌표가 속한 1.2 행정구역(시/도, 시/군/구) 코드 및 명칭을 조회합니다.
         */
        get: operations["resolveRegion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/places/{placeId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 관광지/장소 표준 상세 조회
         * @description 장소 ID(placeId)를 기반으로 기본 정보, 위치 좌표, 개요, 대표 사진, Odii 오디오 매핑 정보를 포함한 상세 정보를 조회합니다.
         */
        get: operations["canonicalPlace"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/operations/moderation/queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 운영자 검수 대기열 큐 조회
         * @description 운영자가 검수해야 할 신고 목록 및 대기열(Queue) 스냅샷을 조회합니다.
         */
        get: operations["queue"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/odii/stories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 오디 오디오 도슨트 스토리 목록 조회
         * @description 언어, 카테고리, 행정구역 코드를 기반으로 오디 오디오 스토리 목록과 재생 시간, 커서 페이징 결과를 조회합니다.
         */
        get: operations["listStories"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/odii/stories/{storyId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 오디 오디오 도슨트 상세 및 스크립트 조회
         * @description 오디오 스토리 ID를 기반으로 스트리밍 오디오 URL, 전체 자막/스크립트 텍스트, 장소 매핑 정보를 조회합니다.
         */
        get: operations["storyDetail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/members/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 현재 로그인한 내 프로필 조회
         * @description 세션 쿠키 기반으로 현재 인증된 회원의 ID 및 닉네임 정보를 조회합니다.
         */
        get: operations["currentMember"];
        put?: never;
        post?: never;
        /**
         * 회원 탈퇴 및 계정 삭제 요청
         * @description 회원 탈퇴를 접수하고 세션을 즉시 만료시키며 비식별화/삭제 프로세스를 시작합니다.
         */
        delete: operations["deleteCurrentMember"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 내 활동 타임라인 조회 (월별 그룹화)
         * @description 특정 월(YYYY-MM)에 발생한 나의 활동(방문 후기 작성, 여정 저장, 장소 찜하기, 오디오 도슨트 청취/북마크)을 일자별 그룹으로 묶어 커서 페이징 조회합니다.
         */
        get: operations["getTimeline"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/journey-threads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 내 여정 탐색 대화 스레드 히스토리 목록 조회
         * @description 로그인한 회원이 진행했던 AI 여정 탐색 스레드 목록을 최신순으로 커서 페이징 조회합니다.
         */
        get: operations["list_2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/journey-threads/{threadId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 여정 탐색 대화 스레드 상세 및 대화 턴 히스토리 조회
         * @description 스레드 ID를 기반으로 대화 질의 내용, AI 생성 상태, 추천 결과, 턴별 변경 이력을 상세 조회합니다.
         */
        get: operations["get_1"];
        put?: never;
        post?: never;
        /**
         * 여정 탐색 대화 스레드 삭제
         * @description 대화 스레드 기록을 삭제합니다.
         */
        delete: operations["delete_1"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/map/places": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 지도 뷰포트/영역 기반 장소 검색
         * @description 지도의 바운딩 박스(minLng,minLat,maxLng,maxLat) 또는 중심점(lat, lng, radius) 기반으로 화면 내 한옥 및 관광지 목록을 조회합니다.
         */
        get: operations["listMapPlaces"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/insights/observations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 지역별 관측 데이터 및 방문 메트릭 시계열 조회
         * @description 특정 행정구역(regionCode)의 기간별(from ~ to) 방문 통계, 체류 시간, 선호도 등 관측 지표 시계열 목록을 조회합니다.
         */
        get: operations["listObservations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/insights/heatmap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 지도 히트맵 통계 지표 조회
         * @description 특정 기준일자(date)와 지역 기준의 지도 히트맵 집계 데이터를 조회합니다.
         */
        get: operations["heatmap"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hanoks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 한옥 목록 조회 및 검색
         * @description 키워드, 행정구역 코드, 카테고리(STAY, EXPERIENCE, HISTORIC), 대표 사진 유무를 기반으로 커서 페이징 방식의 한옥 목록을 조회합니다.
         */
        get: operations["listHanoks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hanoks/{placeId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 한옥 전용 상세 정보 조회
         * @description 한옥 ID를 기반으로 건축 양식, 숙박/체험 정보, 편의시설, 에디토리얼 태그를 포함한 한옥 특화 상세 정보를 조회합니다.
         */
        get: operations["hanok"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hanoks/monthly": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 이달의 한옥 에디토리얼 조회
         * @description 특정 연/월(YYYY-MM)의 큐레이션된 이달의 한옥 매거진 에디토리얼 콘텐츠를 조회합니다.
         */
        get: operations["monthly"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/explorations/{explorationId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * AI 여정 탐색 상태 및 스냅샷 조회
         * @description 탐색 세션 ID를 기반으로 현재 확정된 코스, 제안 목록, 장소 상세 하이드레이션 데이터, 액션 상태를 조회합니다.
         */
        get: operations["get_2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/explorations/{explorationId}/runs/{runId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * AI 실행 런(Run) 단건 상태 조회
         * @description 비동기로 실행 중인 AI 추천 런(Run)의 현재 진행 상태(QUEUED, RUNNING, COMPLETED, FAILED, CANCELLED)를 조회합니다.
         */
        get: operations["getRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/explorations/{explorationId}/runs/{runId}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * AI 여정 생성 실시간 SSE 이벤트 스트림
         * @description AI 여정 생성 과정(토큰 스트리밍, 코스 구성, 제안 생성, 상태 전이)을 Server-Sent Events(text/event-stream)로 실시간 수신합니다. Last-Event-ID 헤더를 통한 재연결 및 유실 이벤트 리플레이를 지원합니다.
         */
        get: operations["events"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/visit-reviews/{reviewId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * 방문 후기 삭제
         * @description 작성자 본인의 방문 후기를 삭제합니다.
         */
        delete: operations["deleteReview"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApiErrorResponse: {
            schemaVersion?: string;
            code?: string;
            message?: string;
            requestId?: string;
            details?: {
                [key: string]: Record<string, never>;
            };
        };
        CorpusAcknowledgement: {
            contractVersion?: string;
            revisionId?: string;
            manifestHash?: string;
            /** @enum {string} */
            status?: "ACTIVE" | "REJECTED";
            /** Format: int32 */
            documentCount?: number;
            /** Format: int32 */
            tombstoneCount?: number;
            embeddingProfile?: string;
            /** Format: date-time */
            completedAt?: string;
            errorCode?: string;
        };
        /** @description 방문 후기 신고 요청 DTO */
        ReportRequest: {
            /**
             * @description 신고 사유 (SPAM, ABUSE, OFFENSIVE, COPYRIGHT, PRIVACY, OTHER)
             * @example SPAM
             */
            reason?: string;
            /**
             * @description 신고 상세 설명
             * @example 장소와 전혀 무관한 광고성 글입니다.
             */
            detail?: string;
        };
        CreateRequest: {
            /** Format: uuid */
            explorationId?: string;
            /** Format: int32 */
            baseVersion?: number;
            title?: string;
            unknownFields?: {
                [key: string]: Record<string, never>;
            };
        };
        /** @description 방문 후기 작성 요청 DTO */
        CreateReviewRequest: {
            /**
             * @description 후기 본문 내용 (최대 1,000자)
             * @example 한옥의 고즈넉한 정취와 마당의 풍경이 정말 인상 깊었습니다.
             */
            text?: string;
        };
        /** @description 운영자 검수 조치 요청 DTO */
        ModerationRequest: {
            /**
             * @description 변경할 다음 상태 (PUBLISHED, HIDDEN, DELETED)
             * @example HIDDEN
             */
            nextStatus?: string;
            /**
             * @description 조치 사유 (POLICY_VIOLATION, SPAM_CONFIRMED, FALSE_REPORT, OTHER)
             * @example SPAM_CONFIRMED
             */
            reason?: string;
        };
        RunAcceptedResponse: {
            schemaVersion?: string;
            /** Format: uuid */
            explorationId?: string;
            /** Format: uuid */
            runId?: string;
            /** Format: int32 */
            stateVersion?: number;
            runUrl?: string;
            eventsUrl?: string;
            snapshotUrl?: string;
        };
        ClarificationAnswer: {
            clarificationId?: string;
            choiceId?: string;
            text?: string;
        };
        CreateTurnRequest: {
            /** Format: uuid */
            clientTurnId?: string;
            /** Format: int32 */
            baseVersion?: number;
            query?: string;
            clarificationAnswer?: components["schemas"]["ClarificationAnswer"];
        };
        ClarificationResponse: {
            id?: string;
            reason?: string;
            question?: string;
            choices?: Record<string, never>[];
            allowFreeText?: boolean;
        };
        RunResponse: {
            schemaVersion?: string;
            /** Format: uuid */
            runId?: string;
            status?: string;
            engine?: string;
            degradedReason?: string;
            stage?: string;
            outcome?: string;
            clarification?: components["schemas"]["ClarificationResponse"];
            /** Format: int32 */
            retryAfterMs?: number;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            startedAt?: string;
            /** Format: date-time */
            deadlineAt?: string;
            error?: Record<string, never>;
        };
        ActionBody: {
            type?: string;
            resourceRef?: components["schemas"]["ResourceBody"];
            /** Format: uuid */
            proposalId?: string;
        };
        ActionRequest: {
            /** Format: uuid */
            commandId?: string;
            /** Format: int32 */
            baseVersion?: number;
            action?: components["schemas"]["ActionBody"];
        };
        ResourceBody: {
            type?: string;
            id?: string;
        };
        ExplorationResponse: {
            schemaVersion?: string;
            /** Format: uuid */
            explorationId?: string;
            /** Format: int32 */
            stateVersion?: number;
            board?: Record<string, never>;
            pinnedRefs?: Record<string, never>[];
            excludedRefs?: Record<string, never>[];
            unavailableRefs?: Record<string, never>[];
            execution?: {
                [key: string]: Record<string, never>;
            };
            latestRun?: components["schemas"]["RunResponse"];
            pendingProposal?: Record<string, never>;
            recentHistory?: Record<string, never>[];
            /** Format: date-time */
            updatedAt?: string;
        };
        CorpusManifest: {
            contractVersion?: string;
            revisionId?: string;
            /** Format: date-time */
            publishedAt?: string;
            manifestHash?: string;
            documents?: components["schemas"]["CorpusManifestEntry"][];
        };
        CorpusManifestEntry: {
            documentId?: string;
            kind?: string;
            documentHash?: string;
            state?: string;
            contentUrl?: string;
        };
        CorpusDocument: {
            contractVersion?: string;
            revisionId?: string;
            documentId?: string;
            kind?: string;
            sourceId?: string;
            sourceRevision?: string;
            provenanceId?: string;
            category?: string;
            region?: string;
            publicationEligible?: boolean;
            text?: string;
            documentHash?: string;
        };
        /** @description CSRF 토큰 발급 응답 */
        CsrfTokenResponse: {
            /**
             * @description CSRF 검증용 마스킹 토큰
             * @example d94b15c7-8c35-430b-9304-4b53efba8a19
             */
            token?: string;
            /**
             * @description 클라이언트가 전송할 요청 헤더 키
             * @example X-CSRF-TOKEN
             */
            headerName?: string;
        };
        SseEmitter: {
            /** Format: int64 */
            timeout?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    like: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description 후기 고유 식별자 (UUID)
                 * @example a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d
                 */
                reviewId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 좋아요 등록 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
            /** @description 로그인 세션 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description 본인 작성 후기 좋아요 금지 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description 후기를 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    unlike: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description 후기 고유 식별자 (UUID)
                 * @example a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d
                 */
                reviewId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 좋아요 취소 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
            /** @description 로그인 세션 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description 후기를 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    savePlace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description 장소 고유 식별자
                 * @example place-seoul-bukchon-001
                 */
                placeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 장소 저장 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
            /** @description 로그인 세션 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description 장소를 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description 최대 저장 한도 초과 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    deletePlace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description 장소 고유 식별자
                 * @example place-seoul-bukchon-001
                 */
                placeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 저장 취소 완료 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
            /** @description 로그인 세션 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    saveOdii: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description 오디 스토리 ID
                 * @example story-gyeongbokgung-01
                 */
                storyId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 오디오 스토리 저장 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
            /** @description 로그인 세션 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description 오디오 스토리를 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description 최대 저장 한도 초과 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    deleteOdii: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description 오디 스토리 ID
                 * @example story-gyeongbokgung-01
                 */
                storyId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 저장 취소 완료 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
            /** @description 로그인 세션 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    acknowledge: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description 코퍼스 리비전 식별자
                 * @example rev-2026-09-001
                 */
                revisionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CorpusAcknowledgement"];
            };
        };
        responses: {
            /** @description 수신확인 처리 접수 완료 */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 리비전 불일치 또는 검증 오류 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    report: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description 멱등성 키
                 * @example 9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d
                 */
                "Idempotency-Key"?: string;
            };
            path: {
                /**
                 * @description 신고할 후기 UUID
                 * @example a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d
                 */
                reviewId: string;
            };
            cookie?: never;
        };
        /** @description 신고 요청 본문 */
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReportRequest"];
            };
        };
        responses: {
            /** @description 신고 접수 완료 */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
            /** @description 유효하지 않은 신고 사유 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description 로그인 세션 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description 본인 작성 후기 신고 금지 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description 후기를 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    list: {
        parameters: {
            query?: {
                /**
                 * @description 조회 개수 (기본값 20)
                 * @example 20
                 */
                limit?: number;
                /** @description 다음 페이지 커서 토큰 */
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 저장 여정 목록 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
            /** @description 로그인 세션 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description 멱등성 키
                 * @example 9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d
                 */
                "Idempotency-Key"?: string;
            };
            path?: never;
            cookie?: never;
        };
        /** @description 여정 저장 요청 본문 */
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CreateRequest"];
            };
        };
        responses: {
            /** @description 여정 저장 성공 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
            /** @description 유효하지 않은 요청 데이터 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description 로그인 세션 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description 진행 중인 AI 런이 있거나 최대 저장 한도(30개) 초과 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    resume: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description 멱등성 키
                 * @example 9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d
                 */
                "Idempotency-Key"?: string;
            };
            path: {
                /**
                 * @description 저장 여정 UUID
                 * @example a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d
                 */
                savedJourneyId: string;
            };
            cookie?: never;
        };
        /** @description 빈 JSON 객체 */
        requestBody?: {
            content: {
                "application/json": {
                    [key: string]: Record<string, never>;
                };
            };
        };
        responses: {
            /** @description AI 탐색 재개 세션 생성 완료 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
            /** @description 로그인 세션 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description 저장 여정을 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    listPlaceVisitReviews: {
        parameters: {
            query?: {
                /**
                 * @description 조회 건수 (기본값 20)
                 * @example 20
                 */
                limit?: number;
                /** @description 다음 페이지 커서 토큰 */
                cursor?: string;
            };
            header?: never;
            path: {
                /**
                 * @description 장소 고유 식별자
                 * @example place-seoul-bukchon-001
                 */
                placeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 장소별 방문 후기 목록 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
            /** @description 유효하지 않은 요청 또는 커서 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description 후기 서비스 일시적 이용 불가 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    createReview: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description 멱등성 보장 키 (UUID)
                 * @example 9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d
                 */
                "Idempotency-Key"?: string;
            };
            path: {
                /**
                 * @description 장소 고유 식별자
                 * @example place-seoul-bukchon-001
                 */
                placeId: string;
            };
            cookie?: never;
        };
        /** @description 방문 후기 내용 */
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateReviewRequest"];
            };
        };
        responses: {
            /** @description 방문 후기 작성 성공 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
            /** @description 유효하지 않은 본문 내용 (글자 수 초과 또는 비어있음) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description 로그인 세션 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description 장소를 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    moderate: {
        parameters: {
            query?: never;
            header?: {
                /** @description 운영자 인증 헤더 (Bearer 토큰) */
                Authorization?: string;
                /**
                 * @description 운영자 식별자 (ID/이메일)
                 * @example operator-admin
                 */
                "X-OnMaru-Operator"?: string;
            };
            path: {
                /**
                 * @description 검수할 후기 UUID
                 * @example a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d
                 */
                reviewId: string;
            };
            cookie?: never;
        };
        /** @description 검수 조치 본문 */
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModerationRequest"];
            };
        };
        responses: {
            /** @description 검수 상태 변경 완료 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
            /** @description 유효하지 않은 검수 파라미터 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description 운영자 인증 실패 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description 후기를 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    create_1: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description 멱등성 키
                 * @example 9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d
                 */
                "Idempotency-Key"?: string;
            };
            path?: never;
            cookie?: never;
        };
        /** @description 여정 탐색 시작 요청 DTO */
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CreateRequest"];
            };
        };
        responses: {
            /** @description 여정 생성 런 접수 완료 (SSE 또는 폴링으로 상태 확인) */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RunAcceptedResponse"];
                };
            };
            /** @description 유효하지 않은 요청 본문 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description 동시 실행 정원 초과 (Admission Throttled) */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    createTurn: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description 멱등성 키
                 * @example 9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d
                 */
                "Idempotency-Key"?: string;
            };
            path: {
                /**
                 * @description 탐색 세션 UUID
                 * @example a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d
                 */
                explorationId: string;
            };
            cookie?: never;
        };
        /** @description 대화 턴 추가 요청 DTO */
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CreateTurnRequest"];
            };
        };
        responses: {
            /** @description 대화 턴 런 접수 완료 */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RunAcceptedResponse"];
                };
            };
            /** @description 유효하지 않은 턴 요청 본문 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description 동시 실행 정원 초과 */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    cancelRun: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description 멱등성 키
                 * @example 9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d
                 */
                "Idempotency-Key"?: string;
            };
            path: {
                /**
                 * @description 탐색 세션 UUID
                 * @example a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d
                 */
                explorationId: string;
                /**
                 * @description AI 실행 런 UUID
                 * @example c1d2e3f4-a5b6-7c8d-9e0f-1a2b3c4d5e6f
                 */
                runId: string;
            };
            cookie?: never;
        };
        /** @description 빈 JSON 객체 */
        requestBody?: {
            content: {
                "application/json": {
                    [key: string]: Record<string, never>;
                };
            };
        };
        responses: {
            /** @description AI 실행 취소 완료 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RunResponse"];
                };
            };
            /** @description 런 또는 탐색 세션을 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    applyAction: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description 멱등성 키
                 * @example 9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d
                 */
                "Idempotency-Key"?: string;
            };
            path: {
                /**
                 * @description 탐색 세션 UUID
                 * @example a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d
                 */
                explorationId: string;
            };
            cookie?: never;
        };
        /** @description 여정 수정 액션 요청 DTO */
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ActionRequest"];
            };
        };
        responses: {
            /** @description 액션 적용 성공 및 갱신된 스냅샷 반환 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ExplorationResponse"];
                };
            };
            /** @description 유효하지 않은 액션 파라미터 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description 베이스 버전 불일치 (CAS 낙관적 락 충돌) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    [key: string]: Record<string, never>;
                };
            };
        };
        responses: {
            /** @description 로그아웃 완료 및 쿠키 파기 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    manifest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description 코퍼스 리비전 식별자
                 * @example rev-2026-09-001
                 */
                revisionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 매니페스트 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CorpusManifest"];
                };
            };
            /** @description 해당 리비전이 존재하지 않음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    document: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description 코퍼스 리비전 식별자
                 * @example rev-2026-09-001
                 */
                revisionId: string;
                /**
                 * @description 문서 고유 식별자
                 * @example doc-hanok-001
                 */
                documentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 문서 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CorpusDocument"];
                };
            };
            /** @description 해당 리비전 또는 문서가 존재하지 않음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    startLogin: {
        parameters: {
            query?: {
                /**
                 * @description 로그인 완료 후 이동할 프론트엔드 경로
                 * @example /discover
                 */
                returnTo?: string;
                /**
                 * @description 게스트 탐색 세션과 회원 연동을 위한 탐색 UUID
                 * @example a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d
                 */
                explorationId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 카카오 인증 서버로 리다이렉트 */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    completeLogin: {
        parameters: {
            query?: {
                /** @description 카카오 인가 코드 */
                code?: string;
                /** @description OAuth 상태 토큰 (CSRF 방어용) */
                state?: string;
                /** @description 오류 코드 (인증 실패/취소 시) */
                error?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 로그인 성공 후 결과 페이지로 리다이렉트 */
            303: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    csrfToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description CSRF 토큰 및 쿠키 발급 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CsrfTokenResponse"];
                };
            };
        };
    };
    listVisitReviews: {
        parameters: {
            query: {
                /**
                 * @description 조회 범위 스코프 (ALL, REGION, MY)
                 * @example ALL
                 */
                scope: string;
                /**
                 * @description 행정구역 코드 (스코프가 REGION일 때 필수)
                 * @example 11110
                 */
                regionCode?: string;
                /**
                 * @description 조회 건수 (기본값 20)
                 * @example 20
                 */
                limit?: number;
                /** @description 다음 페이지 커서 토큰 */
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 방문 후기 목록 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
            /** @description 유효하지 않은 스코프 또는 커서 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description 후기 서비스 일시적 이용 불가 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    listVisitReviewRegions: {
        parameters: {
            query?: {
                /**
                 * @description 상위 시/도 행정구역 코드 (미입력 시 전국 17개 광역시/도 목록 반환)
                 * @example 11
                 */
                parentRegionCode?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 행정구역 통계 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
            /** @description 유효하지 않은 부모 행정구역 코드 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description 행정구역 서비스 일시적 이용 불가 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    list_1: {
        parameters: {
            query: {
                /**
                 * @description 저장 리소스 타입 (PLACE, ODII_STORY)
                 * @example PLACE
                 */
                type: string;
                /**
                 * @description 조회 개수 (기본값 20, 최대 50)
                 * @example 20
                 */
                limit?: number;
                /** @description 다음 페이지 커서 토큰 */
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 저장 리소스 목록 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
            /** @description 유효하지 않은 타입 또는 파라미터 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description 로그인 세션 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description 저장 여정 UUID
                 * @example a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d
                 */
                savedJourneyId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 저장 여정 상세 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
            /** @description 로그인 세션 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description 저장 여정을 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    delete: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description 멱등성 키
                 * @example 9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d
                 */
                "Idempotency-Key"?: string;
            };
            path: {
                /**
                 * @description 저장 여정 UUID
                 * @example a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d
                 */
                savedJourneyId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 저장 여정 삭제 완료 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
            /** @description 로그인 세션 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description 저장 여정을 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    resolveRegion: {
        parameters: {
            query: {
                /**
                 * @description 위도 (WGS84)
                 * @example 37.5665
                 */
                lat: number;
                /**
                 * @description 경도 (WGS84)
                 * @example 126.978
                 */
                lng: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 행정구역 해석 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
            /** @description 유효하지 않은 좌표 값 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description 행정구역 서비스 일시적 이용 불가 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    canonicalPlace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description 장소 고유 식별자
                 * @example place-seoul-bukchon-001
                 */
                placeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 장소 상세 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
            /** @description 장소를 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description 카탈로그 서비스 일시적 이용 불가 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    queue: {
        parameters: {
            query?: {
                /**
                 * @description 조회 건수 (기본값 100)
                 * @example 100
                 */
                limit?: number;
            };
            header?: {
                /** @description 운영자 인증 헤더 (Bearer 토큰) */
                Authorization?: string;
                /**
                 * @description 운영자 식별자
                 * @example operator-admin
                 */
                "X-OnMaru-Operator"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 검수 대기열 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
            /** @description 유효하지 않은 limit 파라미터 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description 운영자 인증 실패 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    listStories: {
        parameters: {
            query?: {
                /**
                 * @description 해설 언어 코드 (ko-KR, en-US 등)
                 * @example ko-KR
                 */
                language?: string;
                /**
                 * @description 스토리 카테고리
                 * @example HISTORIC
                 */
                category?: string;
                /**
                 * @description 행정구역 코드
                 * @example 11110
                 */
                regionCode?: string;
                /**
                 * @description 조회 건수 (기본값 20)
                 * @example 20
                 */
                limit?: string;
                /** @description 다음 페이지 커서 토큰 */
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 오디오 스토리 목록 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
            /** @description 유효하지 않은 요청 또는 만료된 커서 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description 오디 서비스 일시적 이용 불가 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    storyDetail: {
        parameters: {
            query?: {
                /**
                 * @description 해설 언어 코드
                 * @example ko-KR
                 */
                language?: string;
            };
            header?: never;
            path: {
                /**
                 * @description 오디 스토리 고유 ID
                 * @example story-gyeongbokgung-01
                 */
                storyId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 오디오 스토리 상세 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
            /** @description 오디오 스토리를 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description 오디 서비스 일시적 이용 불가 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    currentMember: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 회원 정보 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
            /** @description 로그인 세션 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    deleteCurrentMember: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 회원 탈퇴 요청 접수 완료 */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
            /** @description 로그인 세션 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    getTimeline: {
        parameters: {
            query?: {
                /**
                 * @description 조회 대상 연/월 (YYYY-MM, 미입력 시 이번 달)
                 * @example 2026-09
                 */
                month?: string;
                /**
                 * @description 조회 건수 (기본값 20, 최대 50)
                 * @example 20
                 */
                limit?: number;
                /** @description 다음 페이지 커서 토큰 */
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 타임라인 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
            /** @description 유효하지 않은 월(month) 형식 또는 커서 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description 로그인 세션 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    list_2: {
        parameters: {
            query?: {
                /**
                 * @description 조회 개수 (기본값 20)
                 * @example 20
                 */
                limit?: number;
                /** @description 다음 페이지 커서 토큰 */
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 스레드 목록 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
            /** @description 로그인 세션 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    get_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description 스레드 UUID
                 * @example a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d
                 */
                threadId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 스레드 상세 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
            /** @description 로그인 세션 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description 스레드를 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    delete_1: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description 멱등성 키
                 * @example 9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d
                 */
                "Idempotency-Key"?: string;
            };
            path: {
                /**
                 * @description 스레드 UUID
                 * @example a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d
                 */
                threadId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 스레드 삭제 완료 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
            /** @description 로그인 세션 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description 스레드를 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    listMapPlaces: {
        parameters: {
            query?: {
                /**
                 * @description 응답 언어 (기본값 ko-KR)
                 * @example ko-KR
                 */
                language?: string;
                /**
                 * @description 행정구역 코드 (시/도 또는 시/군/구)
                 * @example 11110
                 */
                regionCode?: string;
                /**
                 * @description 지도 바운딩 박스 (minLng,minLat,maxLng,maxLat)
                 * @example 126.97,37.56,127.01,37.60
                 */
                bbox?: string;
                /**
                 * @description 중심 위도 (WGS84)
                 * @example 37.58
                 */
                lat?: number;
                /**
                 * @description 중심 경도 (WGS84)
                 * @example 126.98
                 */
                lng?: number;
                /**
                 * @description 검색 반경 (미터 단위)
                 * @example 3000
                 */
                radius?: number;
                /**
                 * @description 장소 카테고리 (HANOK, TOURIST, RESTAURANT 등)
                 * @example HANOK
                 */
                category?: string;
                /**
                 * @description 최대 조회 건수 (기본값 20, 최대 100)
                 * @example 20
                 */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 지도 장소 목록 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
            /** @description 유효하지 않은 좌표 바운딩 박스 파라미터 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description 카탈로그 서비스 일시적 이용 불가 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    listObservations: {
        parameters: {
            query: {
                /**
                 * @description 행정구역 코드
                 * @example 11110
                 */
                regionCode: string;
                /**
                 * @description 메트릭 유형 (VISIT_COUNT, REVIEW_COUNT 등)
                 * @example VISIT_COUNT
                 */
                metric?: string;
                /**
                 * @description 시작일 (YYYY-MM-DD)
                 * @example 2026-09-01
                 */
                from?: string;
                /**
                 * @description 종료일 (YYYY-MM-DD)
                 * @example 2026-09-18
                 */
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 관측 데이터 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
            /** @description 유효하지 않은 날짜 또는 파라미터 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    heatmap: {
        parameters: {
            query: {
                /**
                 * @description 행정구역 코드 (미지정 시 전국)
                 * @example 11
                 */
                regionCode?: string;
                /**
                 * @description 기준 일자 (YYYY-MM-DD)
                 * @example 2026-09-18
                 */
                date: string;
                /**
                 * @description 메트릭 유형
                 * @example VISIT_COUNT
                 */
                metric?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 히트맵 데이터 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
            /** @description 유효하지 않은 날짜 또는 파라미터 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    listHanoks: {
        parameters: {
            query?: {
                /**
                 * @description 검색 키워드 (한옥 이름 또는 설명)
                 * @example 북촌
                 */
                keyword?: string;
                /**
                 * @description 행정구역 코드 (시/도 또는 시/군/구)
                 * @example 11110
                 */
                regionCode?: string;
                /**
                 * @description 한옥 카테고리 (STAY, EXPERIENCE, HISTORIC)
                 * @example STAY
                 */
                category?: string;
                /**
                 * @description 사진 보유 한옥만 필터링
                 * @example true
                 */
                hasImage?: boolean;
                /**
                 * @description 조회 개수 (기본값 20, 최대 50)
                 * @example 20
                 */
                limit?: number;
                /** @description 다음 페이지 조회를 위한 커서 토큰 */
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 한옥 목록 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
            /** @description 유효하지 않거나 만료된 페이징 커서 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description 카탈로그 서비스 일시적 이용 불가 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    hanok: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description 한옥 고유 식별자
                 * @example hanok-jeonju-hakindang-001
                 */
                placeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 한옥 상세 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
            /** @description 한옥을 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description 카탈로그 서비스 일시적 이용 불가 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    monthly: {
        parameters: {
            query: {
                /**
                 * @description 조회 대상 연/월 (YYYY-MM)
                 * @example 2026-09
                 */
                month: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 에디토리얼 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
            /** @description 카탈로그 서비스 일시적 이용 불가 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    get_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description 탐색 세션 UUID
                 * @example a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d
                 */
                explorationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 여정 탐색 스냅샷 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ExplorationResponse"];
                };
            };
            /** @description 탐색 세션을 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    getRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description 탐색 세션 UUID
                 * @example a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d
                 */
                explorationId: string;
                /**
                 * @description AI 실행 런 UUID
                 * @example c1d2e3f4-a5b6-7c8d-9e0f-1a2b3c4d5e6f
                 */
                runId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 런 상태 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RunResponse"];
                };
            };
            /** @description 런을 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    events: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description 마지막 수신 이벤트 ID (SSE 재연결 시)
                 * @example 42
                 */
                "Last-Event-ID"?: string;
            };
            path: {
                /**
                 * @description 탐색 세션 UUID
                 * @example a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d
                 */
                explorationId: string;
                /**
                 * @description AI 실행 런 UUID
                 * @example c1d2e3f4-a5b6-7c8d-9e0f-1a2b3c4d5e6f
                 */
                runId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SSE 스트림 연결 수립 (text/event-stream) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["SseEmitter"];
                };
            };
            /** @description 런 또는 탐색 세션을 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["SseEmitter"];
                };
            };
        };
    };
    deleteReview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description 삭제할 후기 UUID
                 * @example a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d
                 */
                reviewId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 방문 후기 삭제 완료 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
            /** @description 로그인 세션 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description 후기를 찾을 수 없거나 삭제 권한 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
}
